### ISSUE TITLE
What is type of image in test set?

### ISSUE THREAD

**Issue by ngoanpv** [Davidzhangyuanhan/CelebASpoofChallengeSubmissionExample#1]
Hi @Davidzhangyuanhan , 
I see all images on your example (['494405.png' '494406.png' '494410.png' '494415.png']) are cropped faces. 
I'd like to know images on the test set whether is raw images as public data or processed images (cropped faces)? 
It will affect my evaluation pipeline. 

Thank you!

**Comment by ZhangYuanhan-AI** [comment]
Images in the private test set are cropped faces.

**Comment by ngoanpv** [comment]
Thanks!
