### ISSUE TITLE
Error by test the Docker image locally

### ISSUE THREAD

**Issue by ngoanpv** [Davidzhangyuanhan/CelebASpoofChallengeSubmissionExample#2]
When I run `docker run -it celeba-spoof-challenge-<my_aws_id> python3 local_test.py`
It appear error due to not detect GPU. 
Is the above command correct?
Or  add option **--gpus all** :  `docker run -it --gpus all  celeba-spoof-challenge-<my_aws_id> python3 local_test.py` ?

**Comment by ljeff97** [comment]
You should use "nvidia-docker run" since it uses GPU.
