### ISSUE TITLE
Error at step 2: Build docker image 

### ISSUE THREAD

**Issue by vodanhbk95** [Davidzhangyuanhan/CelebASpoofChallengeSubmissionExample#8]
When i running **`docker build -t celeba-spoof-challenge-<my aws id> .`** I got this error.
> `Sending build context to Docker daemon  176.5MB
> Step 1/6 : FROM pytorch/pytorch:1.5-cuda10.1-cudnn7-runtime
>  ---> a10c611c2731
> Step 2/6 : RUN apt update && apt install -y -q libfontconfig1 libxrender1 libglib2.0-0 libsm6 libxext6 ucspi-tcp
>  ---> Using cache
>  ---> 28544dcff6e1
> Step 3/6 : RUN pip install -i https://pypi.tuna.tsinghua.edu.cn/simple install boto3 opencv-python-headless pillow numpy scipy matplotlib ipython jupyter pandas sympy nose
>  ---> Running in d9d0c12f8a82
> Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
> Collecting install
>   Downloading https://pypi.tuna.tsinghua.edu.cn/packages/f0/a5/fd2eb807a9a593869ee8b7a6bcb4ad84a6eb31cef5c24d1bfbf7c938c13f/install-1.3.4-py3-none-any.whl (3.1 kB)
> Collecting boto3
>   Downloading https://pypi.tuna.tsinghua.edu.cn/packages/4b/b9/88fbe33f4f4862b06eed9e1fb05abb8883b0bf2683a87f21c45d597adc5a/boto3-1.15.17-py2.py3-none-any.whl (129 kB)
> Collecting opencv-python-headless
>   Downloading https://pypi.tuna.tsinghua.edu.cn/packages/75/d8/72fc2b7dc38e36a1c66fa672d91c8158481c433f67ec45585465bc0aedcf/opencv_python_headless-4.4.0.44-cp37-cp37m-manylinux2014_x86_64.whl (36.7 MB)
> ERROR: Exception:
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/urllib3/contrib/pyopenssl.py", line 313, in recv_into
>     return self.connection.recv_into(*args, **kwargs)
>   File "/opt/conda/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1840, in recv_into
>     self._raise_ssl_error(self._ssl, result)
>   File "/opt/conda/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1646, in _raise_ssl_error
>     raise WantReadError()
> OpenSSL.SSL.WantReadError
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 425, in _error_catcher
>     yield
>   File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 507, in read
>     data = self._fp.read(amt) if not fp_closed else b""
>   File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 62, in read
>     data = self.__fp.read(amt)
>   File "/opt/conda/lib/python3.7/http/client.py", line 457, in read
>     n = self.readinto(b)
>   File "/opt/conda/lib/python3.7/http/client.py", line 501, in readinto
>     n = self.fp.readinto(b)
>   File "/opt/conda/lib/python3.7/socket.py", line 589, in readinto
>     return self._sock.recv_into(b)
>   File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/urllib3/contrib/pyopenssl.py", line 326, in recv_into
>     raise timeout("The read operation timed out")
> socket.timeout: The read operation timed out
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 186, in _main
>     status = self.run(options, args)
>   File "/opt/conda/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 331, in run
>     resolver.resolve(requirement_set)
>   File "/opt/conda/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 177, in resolve
>     discovered_reqs.extend(self._resolve_one(requirement_set, req))
>   File "/opt/conda/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 333, in _resolve_one
>     abstract_dist = self._get_abstract_dist_for(req_to_install)
>   File "/opt/conda/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 282, in _get_abstract_dist_for
>     abstract_dist = self.preparer.prepare_linked_requirement(req)
>   File "/opt/conda/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 482, in prepare_linked_requirement
>     hashes=hashes,
>   File "/opt/conda/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 287, in unpack_url
>     hashes=hashes,
>   File "/opt/conda/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 159, in unpack_http_url
>     link, downloader, temp_dir.path, hashes
>   File "/opt/conda/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 303, in _download_http_url
>     for chunk in download.chunks:
>   File "/opt/conda/lib/python3.7/site-packages/pip/_internal/utils/ui.py", line 160, in iter
>     for x in it:
>   File "/opt/conda/lib/python3.7/site-packages/pip/_internal/network/utils.py", line 39, in response_chunks
>     decode_content=False,
>   File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 564, in stream
>     data = self.read(amt=amt, decode_content=decode_content)
>   File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 529, in read
>     raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
>   File "/opt/conda/lib/python3.7/contextlib.py", line 130, in __exit__
>     self.gen.throw(type, value, traceback)
>   File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 430, in _error_catcher
>     raise ReadTimeoutError(self._pool, None, "Read timed out.")
> pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='pypi.tuna.tsinghua.edu.cn', port=443): Read timed out.
> The command '/bin/sh -c pip install -i https://pypi.tuna.tsinghua.edu.cn/simple install boto3 opencv-python-headless pillow numpy scipy matplotlib ipython jupyter pandas sympy nose' returned a non-zero code: 2`
I am beginer with docker so please help me.

**Comment by ngoanpv** [comment]
` HTTPSConnectionPool(host='pypi.tuna.tsinghua.edu.cn', port=443): Read timed out.`
This is a network problem.
So, try again later or just remove the site `https://pypi.tuna.tsinghua.edu.cn/simple` and install by pip normally.

**Comment by vodanhbk95** [comment]
@ngoanpv 
many thanks for your quickly reply. It causes of my network connection. After retry a few times, I have completely build this docker.
